### ISSUE TITLE
Panic in the distributor

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/cortex#190]
```
panic: runtime error: slice bounds out of range

goroutine 225 [running]:
panic(0xaf7560, 0xc4200160a0)
    /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/weaveworks/cortex/chunk.(*AWSStore).lookupChunksForMatcher(0xc42026c640, 0x7fe601c4b4d0, 0xc420484fc0, 0xc42014de67, 0x1, 0x7ffdacdb3920, 0xc, 0xc4206e8180, 0x6, 0xc4206c26e0, ...)
    /go/src/github.com/weaveworks/cortex/chunk/chunk_store.go:572 +0xff7
github.com/weaveworks/cortex/chunk.(*AWSStore).lookupChunksFor.func1(0xc42026c640, 0x7fe601c4b4d0, 0xc420484fc0, 0xc42014de67, 0x1, 0x7ffdacdb3920, 0xc, 0xc4206e8180, 0x6, 0xc4206c26e0, ...)
    /go/src/github.com/weaveworks/cortex/chunk/chunk_store.go:505 +0xcf
created by github.com/weaveworks/cortex/chunk.(*AWSStore).lookupChunksFor
    /go/src/github.com/weaveworks/cortex/chunk/chunk_store.go:511 +0x17b
panic: runtime error: slice bounds out of range
```

**Comment by tomwilkie** [comment]
This is happen on matchers of the kind `==""`

**Comment by tomwilkie** [comment]
Has to be on non-metric name.
