### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/cortex#240]
```
fatal error: concurrent map writes

goroutine 585 [running]:
runtime.throw(0x9c6e03, 0x15)
	/usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc4200d6648 sp=0xc4200d6628
runtime.mapassign1(0x94b9e0, 0xc4216f9da0, 0xc4200d67e8, 0xc4200d67f8)
	/usr/local/go/src/runtime/hashmap.go:458 +0x8ef fp=0xc4200d6730 sp=0xc4200d6648
github.com/weaveworks/cortex/vendor/github.com/weaveworks/common/middleware.ClientUserHeaderInterceptor(0x7f8798387350, 0xc4212b10b0, 0x9c6ad0, 0x15, 0x9573c0, 0xc4216be520, 0x948a60, 0xe89ec8, 0xc420092000, 0xa01608, ...)
	/go/src/github.com/weaveworks/cortex/vendor/github.com/weaveworks/common/middleware/grpc_auth.go:24 +0x15a fp=0xc4200d6820 sp=0xc4200d6730
github.com/weaveworks/cortex/vendor/github.com/mwitkow/go-grpc-middleware.ChainUnaryClient.func1.1.1(0x7f8798387350, 0xc4212b10b0, 0x9c6ad0, 0x15, 0x9573c0, 0xc4216be520, 0x948a60, 0xe89ec8, 0xc420092000, 0x0, ...)
	/go/src/github.com/weaveworks/cortex/vendor/github.com/mwitkow/go-grpc-middleware/chain.go:58 +0xd4 fp=0xc4200d68a8 sp=0xc4200d6820
github.com/weaveworks/cortex/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingClientInterceptor.func1(0x7f8798387350, 0xc4212b10b0, 0x9c6ad0, 0x15, 0x9573c0, 0xc4216be520, 0x948a60, 0xe89ec8, 0xc420092000, 0xc421401e20, ...)
	/go/src/github.com/weaveworks/cortex/vendor/github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc/client.go:67 +0x45b fp=0xc4200d69f0 sp=0xc4200d68a8
github.com/weaveworks/cortex/vendor/github.com/mwitkow/go-grpc-middleware.ChainUnaryClient.func1.1.1(0x7f8798387350, 0xc42171e180, 0x9c6ad0, 0x15, 0x9573c0, 0xc4216be520, 0x948a60, 0xe89ec8, 0xc420092000, 0x0, ...)
	/go/src/github.com/weaveworks/cortex/vendor/github.com/mwitkow/go-grpc-middleware/chain.go:58 +0xd4 fp=0xc4200d6a78 sp=0xc4200d69f0
github.com/weaveworks/cortex/vendor/github.com/mwitkow/go-grpc-middleware.ChainUnaryClient.func1(0x7f8798387350, 0xc42171e180, 0x9c6ad0, 0x15, 0x9573c0, 0xc4216be520, 0x948a60, 0xe89ec8, 0xc420092000, 0xa01608, ...)
	/go/src/github.com/weaveworks/cortex/vendor/github.com/mwitkow/go-grpc-middleware/chain.go:65 +0x141 fp=0xc4200d6b08 sp=0xc4200d6a78
github.com/weaveworks/cortex/vendor/google.golang.org/grpc.Invoke(0x7f8798387350, 0xc42171e180, 0x9c6ad0, 0x15, 0x9573c0, 0xc4216be520, 0x948a60, 0xe89ec8, 0xc420092000, 0x0, ...)
	/go/src/github.com/weaveworks/cortex/vendor/google.golang.org/grpc/call.go:141 +0xdd fp=0xc4200d6b90 sp=0xc4200d6b08
github.com/weaveworks/cortex.(*ingesterClient).Push(0xc42013e190, 0x7f8798387350, 0xc42171e180, 0xc4216be520, 0x0, 0x0, 0x0, 0x8010102, 0x1, 0xffffffffffffffff)
	/go/src/github.com/weaveworks/cortex/cortex.pb.go:351 +0xd2 fp=0xc4200d6c18 sp=0xc4200d6b90
github.com/weaveworks/cortex/distributor.(*ingesterClient).Push(0xc4216be4e0, 0x7f8798387350, 0xc42171e180, 0xc4216be520, 0x0, 0x0, 0x0, 0x64276b1, 0xc4200d6cd8, 0x537092)
	<autogenerated>:8 +0x92 fp=0xc4200d6c78 sp=0xc4200d6c18
github.com/weaveworks/cortex/distributor.(*Distributor).sendSamples.func1(0x7f8798387350, 0xc42171e180, 0xe665e0, 0xc4200170b0)
	/go/src/github.com/weaveworks/cortex/distributor/distributor.go:330 +0xa5 fp=0xc4200d6ce8 sp=0xc4200d6c78
github.com/weaveworks/cortex/vendor/github.com/weaveworks/common/instrument.TimeRequestHistogramStatus(0x7f8798387350, 0xc420e96db0, 0x9c7d34, 0x17, 0xc42016a150, 0xa013d8, 0xc4200d6ec8, 0xc42013e190, 0xc420092000)
	/go/src/github.com/weaveworks/cortex/vendor/github.com/weaveworks/common/instrument/instrument.go:45 +0x14d fp=0xc4200d6dc8 sp=0xc4200d6ce8
github.com/weaveworks/cortex/vendor/github.com/weaveworks/common/instrument.TimeRequestHistogram(0x7f8798387350, 0xc420e96db0, 0x9c7d34, 0x17, 0xc42016a150, 0xc4200d6ec8, 0x5, 0xc420daa6b8)
	/go/src/github.com/weaveworks/cortex/vendor/github.com/weaveworks/common/instrument/instrument.go:27 +0x70 fp=0xc4200d6e20 sp=0xc4200d6dc8
github.com/weaveworks/cortex/distributor.(*Distributor).sendSamples(0xc4201f4420, 0x7f8798387350, 0xc420e96db0, 0xc421363420, 0xc421085c00, 0x64, 0x80, 0x57c1e4, 0xc4213e94f0)
	/go/src/github.com/weaveworks/cortex/distributor/distributor.go:332 +0x1d5 fp=0xc4200d6f08 sp=0xc4200d6e20
github.com/weaveworks/cortex/distributor.(*Distributor).Push.func1(0xc420b946c0, 0xc4201f4420, 0x7f8798387350, 0xc420e96db0, 0xc421363420, 0xc421085c00, 0x64, 0x80)
	/go/src/github.com/weaveworks/cortex/distributor/distributor.go:301 +0x7a fp=0xc4200d6f70 sp=0xc4200d6f08
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4200d6f78 sp=0xc4200d6f70
created by github.com/weaveworks/cortex/distributor.(*Distributor).Push
	/go/src/github.com/weaveworks/cortex/distributor/distributor.go:302 +0x7e7
```

**Comment by tomwilkie** [comment]
Bugs in the grpc middleware, didn't catch it locally as we only have a single ingester.  Contexts are supposed to be sharable, which means we should have treated the map as immutable.
