### ISSUE TITLE
Ingesters crashlooping

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/cortex#27]
```
time="2016-09-20T20:50:48Z" level=info msg="Flushing 1 chunks" source="frankenstein.go:468" 
panic: runtime error: slice bounds out of range

goroutine 98074 [running]:
panic(0xd68a20, 0xc820014030)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/weaveworks/frankenstein/vendor/github.com/prometheus/prometheus/storage/local.(*Ingester).flushSeries(0xc820114540, 0x7fc41d6d9c90, 0xc822b09050, 0xc820256c60, 0x9842fa55f203a838, 0xc820321420, 0xc820641e00, 0x0, 0x0)
    /go/src/github.com/weaveworks/frankenstein/vendor/github.com/prometheus/prometheus/storage/local/frankenstein.go:476 +0x5f8
github.com/weaveworks/frankenstein/vendor/github.com/prometheus/prometheus/storage/local.(*Ingester).flushAllSeries.func1(0xc820114540, 0x7fc41d6d9c90, 0xc822b09050, 0xc820256c60, 0xc821466860, 0x0, 0xc821466850)
    /go/src/github.com/weaveworks/frankenstein/vendor/github.com/prometheus/prometheus/storage/local/frankenstein.go:439 +0x84
created by github.com/weaveworks/frankenstein/vendor/github.com/prometheus/prometheus/storage/local.(*Ingester).flushAllSeries
    /go/src/github.com/weaveworks/frankenstein/vendor/github.com/prometheus/prometheus/storage/local/frankenstein.go:444 +0x181
```

**Comment by tomwilkie** [comment]
I believe this if fixed now.
