### ISSUE TITLE
Flush routine can deadlock in gRPC (Bigtable backend)

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/cortex#586]
```
goroutine 163 [select, 1728 minutes]:
github.com/weaveworks/cortex/vendor/google.golang.org/grpc/transport.(*recvBufferReader).Read(0xc425c4d580, 0xc422910770, 0x5, 0x5, 0x0, 0x0, 0x0)
	/go/src/github.com/weaveworks/cortex/vendor/google.golang.org/grpc/transport/transport.go:144 +0x556
github.com/weaveworks/cortex/vendor/google.golang.org/grpc/transport.(*Stream).Read(0xc42d2d90e0, 0xc422910770, 0x5, 0x5, 0xc430257458, 0x9, 0x1800)
	/go/src/github.com/weaveworks/cortex/vendor/google.golang.org/grpc/transport/transport.go:332 +0x5c
io.ReadAtLeast(0x154b800, 0xc42d2d90e0, 0xc422910770, 0x5, 0x5, 0x5, 0x9, 0x0, 0x0)
	/usr/local/go/src/io/io.go:307 +0xa9
io.ReadFull(0x154b800, 0xc42d2d90e0, 0xc422910770, 0x5, 0x5, 0x46f2bd, 0x0, 0xc430257558)
	/usr/local/go/src/io/io.go:325 +0x58
github.com/weaveworks/cortex/vendor/google.golang.org/grpc.(*parser).recvMsg(0xc422910760, 0x7fffffff, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc430257498)
	/go/src/github.com/weaveworks/cortex/vendor/google.golang.org/grpc/rpc_util.go:218 +0x69
github.com/weaveworks/cortex/vendor/google.golang.org/grpc.recv(0xc422910760, 0x1557d40, 0x15b30b0, 0xc42d2d90e0, 0x0, 0x0, 0xd6b2a0, 0xc4229107a0, 0x7fffffff, 0x0, ...)
	/go/src/github.com/weaveworks/cortex/vendor/google.golang.org/grpc/rpc_util.go:314 +0x4d
github.com/weaveworks/cortex/vendor/google.golang.org/grpc.(*clientStream).RecvMsg(0xc4254929a0, 0xd6b2a0, 0xc4229107a0, 0x0, 0x0)
	/go/src/github.com/weaveworks/cortex/vendor/google.golang.org/grpc/stream.go:376 +0xe6
github.com/weaveworks/cortex/pkg/chunk/gcp.(*instrumentedClientStream).RecvMsg(0xc425c4d5c0, 0xd6b2a0, 0xc4229107a0, 0xc42acc3ba0, 0x155a9e0)
	/go/src/github.com/weaveworks/cortex/pkg/chunk/gcp/instrumentation.go:91 +0x63
github.com/weaveworks/cortex/vendor/google.golang.org/genproto/googleapis/bigtable/v2.(*bigtableMutateRowsClient).Recv(0xc42acc3ba0, 0x7f2fd915e178, 0xc42690bcb0, 0xc42690bf80)
	/go/src/github.com/weaveworks/cortex/vendor/google.golang.org/genproto/googleapis/bigtable/v2/bigtable.pb.go:879 +0x62
github.com/weaveworks/cortex/vendor/cloud.google.com/go/bigtable.(*Table).doApplyBulk(0xc422910500, 0x7f2fd915e178, 0xc42690bcb0, 0xc421923620, 0xc, 0xc, 0x0, 0x0, 0x0, 0x553499, ...)
	/go/src/github.com/weaveworks/cortex/vendor/cloud.google.com/go/bigtable/bigtable.go:671 +0x299
github.com/weaveworks/cortex/vendor/cloud.google.com/go/bigtable.(*Table).ApplyBulk.func1(0x7f2fd915e178, 0xc42690bcb0, 0x0, 0x0)
	/go/src/github.com/weaveworks/cortex/vendor/cloud.google.com/go/bigtable/bigtable.go:603 +0x88
github.com/weaveworks/cortex/vendor/cloud.google.com/go/bigtable/internal/gax.invokeWithRetry(0x7f2fd915e178, 0xc42690bcb0, 0xc42690bf20, 0x0, 0xc42690bf50, 0x5f5e100, 0x77359400, 0x3ff3333333333333, 0x0, 0x0, ...)
	/go/src/github.com/weaveworks/cortex/vendor/cloud.google.com/go/bigtable/internal/gax/invoke.go:53 +0x100
github.com/weaveworks/cortex/vendor/cloud.google.com/go/bigtable/internal/gax.Invoke(0x7f2fd915e178, 0xc42690bcb0, 0xc42690bf20, 0x158fa00, 0x2, 0x2, 0xc, 0xc)
	/go/src/github.com/weaveworks/cortex/vendor/cloud.google.com/go/bigtable/internal/gax/invoke.go:81 +0xc8
github.com/weaveworks/cortex/vendor/cloud.google.com/go/bigtable.(*Table).ApplyBulk(0xc422910500, 0x7f2fd915e178, 0xc42690bcb0, 0xc428353d40, 0xc, 0xc, 0xc421923560, 0xc, 0xc, 0x0, ...)
	/go/src/github.com/weaveworks/cortex/vendor/cloud.google.com/go/bigtable/bigtable.go:615 +0x541
github.com/weaveworks/cortex/pkg/chunk/gcp.(*storageClient).BatchWrite(0xc4201d4400, 0x7f2fd915e178, 0xc427c28120, 0x154d040, 0xc42690b8c0, 0x1, 0x154d040)
	/go/src/github.com/weaveworks/cortex/pkg/chunk/gcp/storage_client.go:96 +0x511
github.com/weaveworks/cortex/pkg/chunk.(*Store).updateIndex(0xc4201c9280, 0x7f2fd915e178, 0xc427c28120, 0xc420744140, 0xa, 0xc421962000, 0x1, 0x1, 0x2, 0x155c680)
	/go/src/github.com/weaveworks/cortex/pkg/chunk/chunk_store.go:113 +0xd5
github.com/weaveworks/cortex/pkg/chunk.(*Store).Put(0xc4201c9280, 0x7f2fd915e178, 0xc427c28120, 0xc421962000, 0x1, 0x1, 0x15f5aea5bb7, 0x15f5c49ebb7)
	/go/src/github.com/weaveworks/cortex/pkg/chunk/chunk_store.go:104 +0x18d
github.com/weaveworks/cortex/pkg/ingester.(*Ingester).flushChunks(0xc420474000, 0x7f2fd915e178, 0xc427c28120, 0x5d7f7098cc991a81, 0xc42f7463c0, 0xc423c77b60, 0x1, 0x2, 0xc430257f30, 0x154fbc0)
	/go/src/github.com/weaveworks/cortex/pkg/ingester/ingester_flush.go:197 +0x2fd
github.com/weaveworks/cortex/pkg/ingester.(*Ingester).flushUserSeries(0xc420474000, 0xc420744140, 0xa, 0x5d7f7098cc991a81, 0x0, 0x0, 0x0)
	/go/src/github.com/weaveworks/cortex/pkg/ingester/ingester_flush.go:170 +0x21f
github.com/weaveworks/cortex/pkg/ingester.(*Ingester).flushLoop(0xc420474000, 0x15)
	/go/src/github.com/weaveworks/cortex/pkg/ingester/ingester_flush.go:120 +0xe4
created by github.com/weaveworks/cortex/pkg/ingester.New
	/go/src/github.com/weaveworks/cortex/pkg/ingester/ingester.go:273 +0xce2
```

**Comment by tomwilkie** [comment]
Similar blocking stack in containerd https://github.com/containerd/containerd/issues/1261

**Comment by tomwilkie** [comment]
Does coincide with a bunch of `2017/10/27 11:15:15 grpc: Server.processUnaryRPC failed to write status stream error: code = Canceled desc = "context canceled"` in the logs.

**Comment by tomwilkie** [comment]
I suspect its not a deadlock per-se, as we're not actually putting a default timeout on these contexts.  Probably a bug somewhere, but it could be server side?

I will:
- Add a timeout to the flush context
- Follow up bigs in gRPC and BigTable.

**Comment by mbrukman** [comment]
/cc: @garye, @sduskis, @igorbernstein2 — any thoughts on this?

**Comment by sduskis** [comment]
Cancel is generally client side originated.  Deadline Exceeded is generally a server-side (assuming no deadline was set).

Timeouts are a good idea.  Limiting the number of mutations to hundreds might also help, if you're not doing so already.

**Comment by tomwilkie** [comment]
> Cancel is generally client side originated.

I don't know if those logs lines are related; they are not from the hung goroutine.  They just started happening around the same time, could be coincidental.

> Deadline Exceeded is generally a server-side (assuming no deadline was set).

Does the server side enforce a default deadline?  If so this issues should never happen, right?

> Limiting the number of mutations to hundreds might also help, if you're not doing so already.

The number of concurrent mutation is limited to 50 per process; this trace above came from a dev environment where only 3 processes we running, not under a lot of load - practically the concurrent mutations would have been in the tens, maximum.

**Comment by sduskis** [comment]
> Does the server side enforce a default deadline? If so this issues should never happen, right?

The default timeout is 5 minutes, so you're right. 

I'm a Java dev.  @garye knows a lot more about GoLang than I do.  He's aware of the issue, and hopefully we'll work on it this week.

**Comment by tomwilkie** [comment]
hit this again (not in a system with the new timeout, mind you):

```
goroutine 136 [select, 1193 minutes]:
github.com/weaveworks/cortex/vendor/google.golang.org/grpc/transport.(*recvBufferReader).Read(0xc52d1c2440, 0xc4e1c0ee90, 0x5, 0x5, 0x0, 0x0, 0x0)
	/go/src/github.com/weaveworks/cortex/vendor/google.golang.org/grpc/transport/transport.go:144 +0x556
github.com/weaveworks/cortex/vendor/google.golang.org/grpc/transport.(*Stream).Read(0xc44f95cea0, 0xc4e1c0ee90, 0x5, 0x5, 0xc55586f458, 0x9, 0x2000)
	/go/src/github.com/weaveworks/cortex/vendor/google.golang.org/grpc/transport/transport.go:332 +0x5c
io.ReadAtLeast(0x154b800, 0xc44f95cea0, 0xc4e1c0ee90, 0x5, 0x5, 0x5, 0x9, 0x0, 0x0)
	/usr/local/go/src/io/io.go:307 +0xa9
io.ReadFull(0x154b800, 0xc44f95cea0, 0xc4e1c0ee90, 0x5, 0x5, 0x46f2bd, 0x0, 0xc55586f558)
	/usr/local/go/src/io/io.go:325 +0x58
github.com/weaveworks/cortex/vendor/google.golang.org/grpc.(*parser).recvMsg(0xc4e1c0ee80, 0x7fffffff, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc55586f498)
	/go/src/github.com/weaveworks/cortex/vendor/google.golang.org/grpc/rpc_util.go:218 +0x69
github.com/weaveworks/cortex/vendor/google.golang.org/grpc.recv(0xc4e1c0ee80, 0x1557d40, 0x15b30b0, 0xc44f95cea0, 0x0, 0x0, 0xd6b2a0, 0xc4e1c0eee0, 0x7fffffff, 0x0, ...)
	/go/src/github.com/weaveworks/cortex/vendor/google.golang.org/grpc/rpc_util.go:314 +0x4d
github.com/weaveworks/cortex/vendor/google.golang.org/grpc.(*clientStream).RecvMsg(0xc42b64e9a0, 0xd6b2a0, 0xc4e1c0eee0, 0x0, 0x0)
	/go/src/github.com/weaveworks/cortex/vendor/google.golang.org/grpc/stream.go:376 +0xe6
github.com/weaveworks/cortex/pkg/chunk/gcp.(*instrumentedClientStream).RecvMsg(0xc52d1c2480, 0xd6b2a0, 0xc4e1c0eee0, 0xc50c6ff280, 0x155a9e0)
	/go/src/github.com/weaveworks/cortex/pkg/chunk/gcp/instrumentation.go:91 +0x63
github.com/weaveworks/cortex/vendor/google.golang.org/genproto/googleapis/bigtable/v2.(*bigtableMutateRowsClient).Recv(0xc50c6ff280, 0x7fd4e1fce828, 0xc567052a20, 0xc567052d20)
	/go/src/github.com/weaveworks/cortex/vendor/google.golang.org/genproto/googleapis/bigtable/v2/bigtable.pb.go:879 +0x62
github.com/weaveworks/cortex/vendor/cloud.google.com/go/bigtable.(*Table).doApplyBulk(0xc450495e60, 0x7fd4e1fce828, 0xc567052a20, 0xc543612140, 0xa, 0xa, 0x0, 0x0, 0x0, 0x553499, ...)
	/go/src/github.com/weaveworks/cortex/vendor/cloud.google.com/go/bigtable/bigtable.go:671 +0x299
github.com/weaveworks/cortex/vendor/cloud.google.com/go/bigtable.(*Table).ApplyBulk.func1(0x7fd4e1fce828, 0xc567052a20, 0x0, 0x0)
	/go/src/github.com/weaveworks/cortex/vendor/cloud.google.com/go/bigtable/bigtable.go:603 +0x88
github.com/weaveworks/cortex/vendor/cloud.google.com/go/bigtable/internal/gax.invokeWithRetry(0x7fd4e1fce828, 0xc567052a20, 0xc567052cc0, 0x0, 0xc567052cf0, 0x5f5e100, 0x77359400, 0x3ff3333333333333, 0x0, 0x0, ...)
	/go/src/github.com/weaveworks/cortex/vendor/cloud.google.com/go/bigtable/internal/gax/invoke.go:53 +0x100
github.com/weaveworks/cortex/vendor/cloud.google.com/go/bigtable/internal/gax.Invoke(0x7fd4e1fce828, 0xc567052a20, 0xc567052cc0, 0x158fa00, 0x2, 0x2, 0xa, 0xa)
	/go/src/github.com/weaveworks/cortex/vendor/cloud.google.com/go/bigtable/internal/gax/invoke.go:81 +0xc8
github.com/weaveworks/cortex/vendor/cloud.google.com/go/bigtable.(*Table).ApplyBulk(0xc450495e60, 0x7fd4e1fce828, 0xc567052a20, 0xc4f4365220, 0xa, 0xa, 0xc5436120a0, 0xa, 0xa, 0x0, ...)
	/go/src/github.com/weaveworks/cortex/vendor/cloud.google.com/go/bigtable/bigtable.go:615 +0x541
github.com/weaveworks/cortex/pkg/chunk/gcp.(*storageClient).BatchWrite(0xc42036e800, 0x7fd4e1fce828, 0xc497fea5a0, 0x154d040, 0xc4c5a2dce0, 0x1, 0x154d040)
	/go/src/github.com/weaveworks/cortex/pkg/chunk/gcp/storage_client.go:96 +0x511
github.com/weaveworks/cortex/pkg/chunk.(*Store).updateIndex(0xc4201d7d00, 0x7fd4e1fce828, 0xc497fea5a0, 0xc420736b10, 0x6, 0xc5ad3798c0, 0x1, 0x1, 0x2, 0x155c680)
	/go/src/github.com/weaveworks/cortex/pkg/chunk/chunk_store.go:113 +0xd5
github.com/weaveworks/cortex/pkg/chunk.(*Store).Put(0xc4201d7d00, 0x7fd4e1fce828, 0xc497fea5a0, 0xc5ad3798c0, 0x1, 0x1, 0x15fc09d6e9e, 0x15fc13f7afe)
	/go/src/github.com/weaveworks/cortex/pkg/chunk/chunk_store.go:104 +0x18d
github.com/weaveworks/cortex/pkg/ingester.(*Ingester).flushChunks(0xc420205680, 0x7fd4e1fce828, 0xc497fea5a0, 0xc2b9aa7cecb28f37, 0xc428b09fb0, 0xc517fef770, 0x1, 0x2, 0xc55586ff30, 0x154fbc0)
	/go/src/github.com/weaveworks/cortex/pkg/ingester/ingester_flush.go:197 +0x2fd
github.com/weaveworks/cortex/pkg/ingester.(*Ingester).flushUserSeries(0xc420205680, 0xc420736b10, 0x6, 0xc2b9aa7cecb28f37, 0x0, 0x0, 0x0)
	/go/src/github.com/weaveworks/cortex/pkg/ingester/ingester_flush.go:170 +0x21f
github.com/weaveworks/cortex/pkg/ingester.(*Ingester).flushLoop(0xc420205680, 0xf)
	/go/src/github.com/weaveworks/cortex/pkg/ingester/ingester_flush.go:120 +0xe4
created by github.com/weaveworks/cortex/pkg/ingester.New
	/go/src/github.com/weaveworks/cortex/pkg/ingester/ingester.go:273 +0xce2
```

**Comment by tomwilkie** [comment]
Since rolling out the context cancellation, I haven't hit this.  Closing.
